// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionScopes sessionContextKey = "session.Scopes"
)

// Defines values for Role.
const (
	Admin  Role = "admin"
	Editor Role = "editor"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Editor:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	AvatarUrl   string `json:"avatarUrl"`
	DisplayName string `json:"displayName"`
	Editing     bool   `json:"editing"`
	Email       string `json:"email"`
	Role        Role   `json:"role"`
}

// Role defines model for Role.
type Role string

// SessionGrant defines model for SessionGrant.
type SessionGrant struct {
	DisplayName string    `json:"displayName"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Role        Role      `json:"role"`
	Token       string    `json:"token"`
}

// TelegramChallenge defines model for TelegramChallenge.
type TelegramChallenge struct {
	// Bot The bot's @username (no @) — the deep link's host handle.
	Bot string `json:"bot"`

	// Code One-time code for the t.me/{bot}?start={code} deep link.
	Code string `json:"code"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// Internal defines model for Internal.
type Internal = Error

// NotConfigured defines model for NotConfigured.
type NotConfigured = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Upstream defines model for Upstream.
type Upstream = Error

// sessionContextKey is the context key for session security scheme
type sessionContextKey string

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RequestMagicLinkJSONBody defines parameters for RequestMagicLink.
type RequestMagicLinkJSONBody struct {
	Email string `json:"email"`

	// Locale UI locale ("ru", "en") picking the email's language; defaults to English.
	Locale *string `json:"locale,omitempty"`
}

// VerifyMagicLinkJSONBody defines parameters for VerifyMagicLink.
type VerifyMagicLinkJSONBody struct {
	Token string `json:"token"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	// DisplayName Public name shown around the campfire.
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`

	// Password At least 8 characters.
	Password string `json:"password"`
}

// RequestTelegramLoginJSONBody defines parameters for RequestTelegramLogin.
type RequestTelegramLoginJSONBody struct {
	// Username Telegram @username (with or without the leading @).
	Username string `json:"username"`
}

// PollTelegramLoginJSONBody defines parameters for PollTelegramLogin.
type PollTelegramLoginJSONBody struct {
	Code string `json:"code"`
}

// CommitContentJSONBody defines parameters for CommitContent.
type CommitContentJSONBody struct {
	Files []struct {
		Content string `json:"content"`
		Path    string `json:"path"`
	} `json:"files"`

	// Message Commit message; defaulted when omitted.
	Message *string `json:"message,omitempty"`
}

// DeleteContentJSONBody defines parameters for DeleteContent.
type DeleteContentJSONBody struct {
	// Message Commit message; defaulted when omitted.
	Message *string `json:"message,omitempty"`

	// Paths Repo-relative paths; each must live under content/ or be a public/images/*.webp file.
	Paths []string `json:"paths"`
}

// GetContentFileParams defines parameters for GetContentFile.
type GetContentFileParams struct {
	// Path Repo-relative path; must live under content/.
	Path string `form:"path" json:"path"`
}

// UploadImageJSONBody defines parameters for UploadImage.
type UploadImageJSONBody struct {
	// ContentBase64 The image bytes, base64-encoded; decoded size capped server-side.
	ContentBase64 string `json:"contentBase64"`

	// Path Repo-relative target; must be public/images/*.webp.
	Path string `json:"path"`
}

// SaveContentJSONBody defines parameters for SaveContent.
type SaveContentJSONBody struct {
	// Content Whole-file text; capped at 256 KiB server-side.
	Content string `json:"content"`

	// Message Commit message; defaulted when omitted.
	Message *string `json:"message,omitempty"`
	Path    string  `json:"path"`

	// Sha Handle from a prior read. Omit to create a new file.
	Sha *string `json:"sha,omitempty"`
}

// EnrichTemplateJSONBody defines parameters for EnrichTemplate.
type EnrichTemplateJSONBody struct {
	// Template The base template body to re-tune; capped well under the content cap.
	Template string `json:"template"`
	Title    string `json:"title"`
}

// TranslateContentJSONBody defines parameters for TranslateContent.
type TranslateContentJSONBody struct {
	// TargetLocale The locale to translate INTO (e.g. "en", "ru").
	TargetLocale string `json:"targetLocale"`

	// Text The whole source file (frontmatter + body); under the content cap.
	Text string `json:"text"`
}

// UpdateMeJSONBody defines parameters for UpdateMe.
type UpdateMeJSONBody struct {
	// AvatarUrl Image shown around the campfire — a URL or an inlined data: URI (browser-downscaled upload). Omit or empty to clear it.
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	DisplayName string  `json:"displayName"`

	// Email Omit or empty for Telegram-only accounts (they have no email).
	Email *string `json:"email,omitempty"`

	// Password At least 8 characters. Omit to keep the current password.
	Password *string `json:"password,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	// AvatarUrl Image shown around the campfire — a URL or an inlined data: URI (browser-downscaled upload). Omit or empty to clear it.
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	DisplayName string  `json:"displayName"`

	// Password At least 8 characters. Omit to keep the current password.
	Password *string `json:"password,omitempty"`
	Role     Role    `json:"role"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RequestMagicLinkJSONRequestBody defines body for RequestMagicLink for application/json ContentType.
type RequestMagicLinkJSONRequestBody RequestMagicLinkJSONBody

// VerifyMagicLinkJSONRequestBody defines body for VerifyMagicLink for application/json ContentType.
type VerifyMagicLinkJSONRequestBody VerifyMagicLinkJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// RequestTelegramLoginJSONRequestBody defines body for RequestTelegramLogin for application/json ContentType.
type RequestTelegramLoginJSONRequestBody RequestTelegramLoginJSONBody

// PollTelegramLoginJSONRequestBody defines body for PollTelegramLogin for application/json ContentType.
type PollTelegramLoginJSONRequestBody PollTelegramLoginJSONBody

// CommitContentJSONRequestBody defines body for CommitContent for application/json ContentType.
type CommitContentJSONRequestBody CommitContentJSONBody

// DeleteContentJSONRequestBody defines body for DeleteContent for application/json ContentType.
type DeleteContentJSONRequestBody DeleteContentJSONBody

// UploadImageJSONRequestBody defines body for UploadImage for application/json ContentType.
type UploadImageJSONRequestBody UploadImageJSONBody

// SaveContentJSONRequestBody defines body for SaveContent for application/json ContentType.
type SaveContentJSONRequestBody SaveContentJSONBody

// EnrichTemplateJSONRequestBody defines body for EnrichTemplate for application/json ContentType.
type EnrichTemplateJSONRequestBody EnrichTemplateJSONBody

// TranslateContentJSONRequestBody defines body for TranslateContent for application/json ContentType.
type TranslateContentJSONRequestBody TranslateContentJSONBody

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody UpdateMeJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(c *gin.Context)
	// Revoke the current session
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Email a one-time sign-in link (the passwordless login)
	// (POST /auth/magic)
	RequestMagicLink(c *gin.Context)
	// Redeem an emailed sign-in token for a session
	// (POST /auth/magic/verify)
	VerifyMagicLink(c *gin.Context)
	// Who am I — the frontend's edit-mode probe
	// (GET /auth/me)
	GetMe(c *gin.Context)
	// Create a viewer account (open self-registration) and sign in
	// (POST /auth/register)
	Register(c *gin.Context)
	// Start a Telegram-username sign-in (the primary login)
	// (POST /auth/telegram)
	RequestTelegramLogin(c *gin.Context)
	// Poll a Telegram sign-in for its session grant
	// (POST /auth/telegram/poll)
	PollTelegramLogin(c *gin.Context)
	// Write one or more content/ files in a SINGLE git commit
	// (POST /content/commit)
	CommitContent(c *gin.Context)
	// Delete one or more content/ files in a SINGLE git commit (a working-tree remove in dev)
	// (DELETE /content/file)
	DeleteContent(c *gin.Context)
	// Read one content/ file (text + opaque sha for concurrency)
	// (GET /content/file)
	GetContentFile(c *gin.Context, params GetContentFileParams)
	// Commit one uploaded image to public/images/ (a git commit in prod)
	// (POST /content/image)
	UploadImage(c *gin.Context)
	// Write one content/ file (a git commit in prod, a working-tree write in dev)
	// (POST /content/save)
	SaveContent(c *gin.Context)
	// Re-tune a blank content template's prompts to a post title (LLM)
	// (POST /content/template)
	EnrichTemplate(c *gin.Context)
	// Translate a content file's prose to another locale (LLM)
	// (POST /content/translate)
	TranslateContent(c *gin.Context)
	// Liveness probe
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// Scaffold endpoint proving a DB round-trip (feeds BackendBadge)
	// (GET /hello)
	GetHello(c *gin.Context)
	// Everyone around the campfire (any signed-in user may look)
	// (GET /users)
	ListUsers(c *gin.Context)
	// Update your own profile (display name, email, avatar, optionally password)
	// (PUT /users/me)
	UpdateMe(c *gin.Context)
	// Admin — edit another user's name, avatar, role, and optionally password
	// (PUT /users/{id})
	UpdateUser(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(string(SessionScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// RequestMagicLink operation middleware
func (siw *ServerInterfaceWrapper) RequestMagicLink(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestMagicLink(c)
}

// VerifyMagicLink operation middleware
func (siw *ServerInterfaceWrapper) VerifyMagicLink(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyMagicLink(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(SessionScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// RequestTelegramLogin operation middleware
func (siw *ServerInterfaceWrapper) RequestTelegramLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestTelegramLogin(c)
}

// PollTelegramLogin operation middleware
func (siw *ServerInterfaceWrapper) PollTelegramLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PollTelegramLogin(c)
}

// CommitContent operation middleware
func (siw *ServerInterfaceWrapper) CommitContent(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CommitContent(c)
}

// DeleteContent operation middleware
func (siw *ServerInterfaceWrapper) DeleteContent(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteContent(c)
}

// GetContentFile operation middleware
func (siw *ServerInterfaceWrapper) GetContentFile(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(SessionScopes), []string{"editor"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContentFileParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", c.Request.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetContentFile(c, params)
}

// UploadImage operation middleware
func (siw *ServerInterfaceWrapper) UploadImage(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadImage(c)
}

// SaveContent operation middleware
func (siw *ServerInterfaceWrapper) SaveContent(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveContent(c)
}

// EnrichTemplate operation middleware
func (siw *ServerInterfaceWrapper) EnrichTemplate(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.EnrichTemplate(c)
}

// TranslateContent operation middleware
func (siw *ServerInterfaceWrapper) TranslateContent(c *gin.Context) {

	c.Set(string(SessionScopes), []string{"editor"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TranslateContent(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetHello operation middleware
func (siw *ServerInterfaceWrapper) GetHello(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHello(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *gin.Context) {

	c.Set(string(SessionScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUsers(c)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(c *gin.Context) {

	c.Set(string(SessionScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMe(c)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(SessionScopes), []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/magic", wrapper.RequestMagicLink)
	router.POST(options.BaseURL+"/auth/magic/verify", wrapper.VerifyMagicLink)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/telegram", wrapper.RequestTelegramLogin)
	router.POST(options.BaseURL+"/auth/telegram/poll", wrapper.PollTelegramLogin)
	router.POST(options.BaseURL+"/content/commit", wrapper.CommitContent)
	router.DELETE(options.BaseURL+"/content/file", wrapper.DeleteContent)
	router.GET(options.BaseURL+"/content/file", wrapper.GetContentFile)
	router.POST(options.BaseURL+"/content/image", wrapper.UploadImage)
	router.POST(options.BaseURL+"/content/save", wrapper.SaveContent)
	router.POST(options.BaseURL+"/content/template", wrapper.EnrichTemplate)
	router.POST(options.BaseURL+"/content/translate", wrapper.TranslateContent)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/hello", wrapper.GetHello)
	router.GET(options.BaseURL+"/users", wrapper.ListUsers)
	router.PUT(options.BaseURL+"/users/me", wrapper.UpdateMe)
	router.PUT(options.BaseURL+"/users/:id", wrapper.UpdateUser)
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalJSONResponse Error

type NotConfiguredJSONResponse Error

type RateLimitedJSONResponse Error

type UnauthorizedJSONResponse Error

type UpstreamJSONResponse Error

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse SessionGrant

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse struct{ RateLimitedJSONResponse }

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLinkRequestObject struct {
	Body *RequestMagicLinkJSONRequestBody
}

type RequestMagicLinkResponseObject interface {
	VisitRequestMagicLinkResponse(w http.ResponseWriter) error
}

type RequestMagicLink200JSONResponse struct {
	Status string `json:"status"`
}

func (response RequestMagicLink200JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLink400JSONResponse struct{ BadRequestJSONResponse }

func (response RequestMagicLink400JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLink429JSONResponse struct{ RateLimitedJSONResponse }

func (response RequestMagicLink429JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RequestMagicLink503JSONResponse Error

func (response RequestMagicLink503JSONResponse) VisitRequestMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMagicLinkRequestObject struct {
	Body *VerifyMagicLinkJSONRequestBody
}

type VerifyMagicLinkResponseObject interface {
	VisitVerifyMagicLinkResponse(w http.ResponseWriter) error
}

type VerifyMagicLink200JSONResponse SessionGrant

func (response VerifyMagicLink200JSONResponse) VisitVerifyMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMagicLink400JSONResponse struct{ BadRequestJSONResponse }

func (response VerifyMagicLink400JSONResponse) VisitVerifyMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMagicLink401JSONResponse Error

func (response VerifyMagicLink401JSONResponse) VisitVerifyMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMagicLink429JSONResponse struct{ RateLimitedJSONResponse }

func (response VerifyMagicLink429JSONResponse) VisitVerifyMagicLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse SessionGrant

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse struct{ BadRequestJSONResponse }

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse Error

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register429JSONResponse struct{ RateLimitedJSONResponse }

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RequestTelegramLoginRequestObject struct {
	Body *RequestTelegramLoginJSONRequestBody
}

type RequestTelegramLoginResponseObject interface {
	VisitRequestTelegramLoginResponse(w http.ResponseWriter) error
}

type RequestTelegramLogin200JSONResponse TelegramChallenge

func (response RequestTelegramLogin200JSONResponse) VisitRequestTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RequestTelegramLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response RequestTelegramLogin400JSONResponse) VisitRequestTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestTelegramLogin429JSONResponse struct{ RateLimitedJSONResponse }

func (response RequestTelegramLogin429JSONResponse) VisitRequestTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RequestTelegramLogin503JSONResponse Error

func (response RequestTelegramLogin503JSONResponse) VisitRequestTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLoginRequestObject struct {
	Body *PollTelegramLoginJSONRequestBody
}

type PollTelegramLoginResponseObject interface {
	VisitPollTelegramLoginResponse(w http.ResponseWriter) error
}

type PollTelegramLogin200JSONResponse SessionGrant

func (response PollTelegramLogin200JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLogin202JSONResponse struct {
	Status string `json:"status"`
}

func (response PollTelegramLogin202JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response PollTelegramLogin400JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLogin401JSONResponse Error

func (response PollTelegramLogin401JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLogin429JSONResponse struct{ RateLimitedJSONResponse }

func (response PollTelegramLogin429JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type PollTelegramLogin503JSONResponse Error

func (response PollTelegramLogin503JSONResponse) VisitPollTelegramLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContentRequestObject struct {
	Body *CommitContentJSONRequestBody
}

type CommitContentResponseObject interface {
	VisitCommitContentResponse(w http.ResponseWriter) error
}

type CommitContent200JSONResponse struct {
	Commit string   `json:"commit"`
	Paths  []string `json:"paths"`
}

func (response CommitContent200JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContent400JSONResponse struct{ BadRequestJSONResponse }

func (response CommitContent400JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CommitContent401JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response CommitContent403JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContent502JSONResponse struct{ UpstreamJSONResponse }

func (response CommitContent502JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CommitContent503JSONResponse struct{ NotConfiguredJSONResponse }

func (response CommitContent503JSONResponse) VisitCommitContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContentRequestObject struct {
	Body *DeleteContentJSONRequestBody
}

type DeleteContentResponseObject interface {
	VisitDeleteContentResponse(w http.ResponseWriter) error
}

type DeleteContent200JSONResponse struct {
	Commit string   `json:"commit"`
	Paths  []string `json:"paths"`
}

func (response DeleteContent200JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteContent400JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteContent401JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteContent403JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent404JSONResponse Error

func (response DeleteContent404JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent502JSONResponse struct{ UpstreamJSONResponse }

func (response DeleteContent502JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteContent503JSONResponse struct{ NotConfiguredJSONResponse }

func (response DeleteContent503JSONResponse) VisitDeleteContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFileRequestObject struct {
	Params GetContentFileParams
}

type GetContentFileResponseObject interface {
	VisitGetContentFileResponse(w http.ResponseWriter) error
}

type GetContentFile200JSONResponse struct {
	Content string `json:"content"`
	Path    string `json:"path"`
	Sha     string `json:"sha"`
}

func (response GetContentFile200JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile400JSONResponse struct{ BadRequestJSONResponse }

func (response GetContentFile400JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetContentFile401JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetContentFile403JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile404JSONResponse Error

func (response GetContentFile404JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile502JSONResponse struct{ UpstreamJSONResponse }

func (response GetContentFile502JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentFile503JSONResponse struct{ NotConfiguredJSONResponse }

func (response GetContentFile503JSONResponse) VisitGetContentFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImageRequestObject struct {
	Body *UploadImageJSONRequestBody
}

type UploadImageResponseObject interface {
	VisitUploadImageResponse(w http.ResponseWriter) error
}

type UploadImage200JSONResponse struct {
	Commit string `json:"commit"`
	Path   string `json:"path"`
}

func (response UploadImage200JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage400JSONResponse struct{ BadRequestJSONResponse }

func (response UploadImage400JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UploadImage401JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage403JSONResponse struct{ ForbiddenJSONResponse }

func (response UploadImage403JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage409JSONResponse Error

func (response UploadImage409JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage413JSONResponse Error

func (response UploadImage413JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage502JSONResponse struct{ UpstreamJSONResponse }

func (response UploadImage502JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type UploadImage503JSONResponse struct{ NotConfiguredJSONResponse }

func (response UploadImage503JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContentRequestObject struct {
	Body *SaveContentJSONRequestBody
}

type SaveContentResponseObject interface {
	VisitSaveContentResponse(w http.ResponseWriter) error
}

type SaveContent200JSONResponse struct {
	Commit string `json:"commit"`
	Path   string `json:"path"`
	Sha    string `json:"sha"`
}

func (response SaveContent200JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent400JSONResponse struct{ BadRequestJSONResponse }

func (response SaveContent400JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SaveContent401JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response SaveContent403JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent409JSONResponse Error

func (response SaveContent409JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent413JSONResponse Error

func (response SaveContent413JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent502JSONResponse struct{ UpstreamJSONResponse }

func (response SaveContent502JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type SaveContent503JSONResponse struct{ NotConfiguredJSONResponse }

func (response SaveContent503JSONResponse) VisitSaveContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplateRequestObject struct {
	Body *EnrichTemplateJSONRequestBody
}

type EnrichTemplateResponseObject interface {
	VisitEnrichTemplateResponse(w http.ResponseWriter) error
}

type EnrichTemplate200JSONResponse struct {
	Body string `json:"body"`
}

func (response EnrichTemplate200JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplate400JSONResponse struct{ BadRequestJSONResponse }

func (response EnrichTemplate400JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplate401JSONResponse struct{ UnauthorizedJSONResponse }

func (response EnrichTemplate401JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplate403JSONResponse struct{ ForbiddenJSONResponse }

func (response EnrichTemplate403JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplate502JSONResponse struct{ UpstreamJSONResponse }

func (response EnrichTemplate502JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type EnrichTemplate503JSONResponse struct{ NotConfiguredJSONResponse }

func (response EnrichTemplate503JSONResponse) VisitEnrichTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContentRequestObject struct {
	Body *TranslateContentJSONRequestBody
}

type TranslateContentResponseObject interface {
	VisitTranslateContentResponse(w http.ResponseWriter) error
}

type TranslateContent200JSONResponse struct {
	Text string `json:"text"`
}

func (response TranslateContent200JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContent400JSONResponse struct{ BadRequestJSONResponse }

func (response TranslateContent400JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TranslateContent401JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response TranslateContent403JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContent502JSONResponse struct{ UpstreamJSONResponse }

func (response TranslateContent502JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type TranslateContent503JSONResponse struct{ NotConfiguredJSONResponse }

func (response TranslateContent503JSONResponse) VisitTranslateContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHelloRequestObject struct {
}

type GetHelloResponseObject interface {
	VisitGetHelloResponse(w http.ResponseWriter) error
}

type GetHello200JSONResponse struct {
	Hits    int    `json:"hits"`
	Message string `json:"message"`
}

func (response GetHello200JSONResponse) VisitGetHelloResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHello500JSONResponse struct{ InternalJSONResponse }

func (response GetHello500JSONResponse) VisitGetHelloResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse struct {
	Users []struct {
		AvatarUrl   *string `json:"avatarUrl,omitempty"`
		DisplayName string  `json:"displayName"`
		Id          int64   `json:"id"`

		// JoinedAt The day the account was created (UTC).
		JoinedAt openapi_types.Date `json:"joinedAt"`
		Role     Role               `json:"role"`

		// You True for the row of the caller's own account.
		You bool `json:"you"`
	} `json:"users"`
}

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListUsers401JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse MeResponse

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe409JSONResponse Error

func (response UpdateMe409JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateUserJSONRequestBody
}

type UpdateUserResponseObject interface {
	VisitUpdateUserResponse(w http.ResponseWriter) error
}

type UpdateUser200JSONResponse struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	DisplayName string  `json:"displayName"`
	Id          int64   `json:"id"`
	Role        Role    `json:"role"`
}

func (response UpdateUser200JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUser400JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUser401JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateUser403JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUser404JSONResponse Error

func (response UpdateUser404JSONResponse) VisitUpdateUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Email a one-time sign-in link (the passwordless login)
	// (POST /auth/magic)
	RequestMagicLink(ctx context.Context, request RequestMagicLinkRequestObject) (RequestMagicLinkResponseObject, error)
	// Redeem an emailed sign-in token for a session
	// (POST /auth/magic/verify)
	VerifyMagicLink(ctx context.Context, request VerifyMagicLinkRequestObject) (VerifyMagicLinkResponseObject, error)
	// Who am I — the frontend's edit-mode probe
	// (GET /auth/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Create a viewer account (open self-registration) and sign in
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Start a Telegram-username sign-in (the primary login)
	// (POST /auth/telegram)
	RequestTelegramLogin(ctx context.Context, request RequestTelegramLoginRequestObject) (RequestTelegramLoginResponseObject, error)
	// Poll a Telegram sign-in for its session grant
	// (POST /auth/telegram/poll)
	PollTelegramLogin(ctx context.Context, request PollTelegramLoginRequestObject) (PollTelegramLoginResponseObject, error)
	// Write one or more content/ files in a SINGLE git commit
	// (POST /content/commit)
	CommitContent(ctx context.Context, request CommitContentRequestObject) (CommitContentResponseObject, error)
	// Delete one or more content/ files in a SINGLE git commit (a working-tree remove in dev)
	// (DELETE /content/file)
	DeleteContent(ctx context.Context, request DeleteContentRequestObject) (DeleteContentResponseObject, error)
	// Read one content/ file (text + opaque sha for concurrency)
	// (GET /content/file)
	GetContentFile(ctx context.Context, request GetContentFileRequestObject) (GetContentFileResponseObject, error)
	// Commit one uploaded image to public/images/ (a git commit in prod)
	// (POST /content/image)
	UploadImage(ctx context.Context, request UploadImageRequestObject) (UploadImageResponseObject, error)
	// Write one content/ file (a git commit in prod, a working-tree write in dev)
	// (POST /content/save)
	SaveContent(ctx context.Context, request SaveContentRequestObject) (SaveContentResponseObject, error)
	// Re-tune a blank content template's prompts to a post title (LLM)
	// (POST /content/template)
	EnrichTemplate(ctx context.Context, request EnrichTemplateRequestObject) (EnrichTemplateResponseObject, error)
	// Translate a content file's prose to another locale (LLM)
	// (POST /content/translate)
	TranslateContent(ctx context.Context, request TranslateContentRequestObject) (TranslateContentResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Scaffold endpoint proving a DB round-trip (feeds BackendBadge)
	// (GET /hello)
	GetHello(ctx context.Context, request GetHelloRequestObject) (GetHelloResponseObject, error)
	// Everyone around the campfire (any signed-in user may look)
	// (GET /users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// Update your own profile (display name, email, avatar, optionally password)
	// (PUT /users/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// Admin — edit another user's name, avatar, role, and optionally password
	// (PUT /users/{id})
	UpdateUser(ctx context.Context, request UpdateUserRequestObject) (UpdateUserResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestMagicLink operation middleware
func (sh *strictHandler) RequestMagicLink(ctx *gin.Context) {
	var request RequestMagicLinkRequestObject

	var body RequestMagicLinkJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestMagicLink(ctx, request.(RequestMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestMagicLink")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RequestMagicLinkResponseObject); ok {
		if err := validResponse.VisitRequestMagicLinkResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyMagicLink operation middleware
func (sh *strictHandler) VerifyMagicLink(ctx *gin.Context) {
	var request VerifyMagicLinkRequestObject

	var body VerifyMagicLinkJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyMagicLink(ctx, request.(VerifyMagicLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyMagicLink")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(VerifyMagicLinkResponseObject); ok {
		if err := validResponse.VisitVerifyMagicLinkResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *gin.Context) {
	var request GetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(ctx *gin.Context) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestTelegramLogin operation middleware
func (sh *strictHandler) RequestTelegramLogin(ctx *gin.Context) {
	var request RequestTelegramLoginRequestObject

	var body RequestTelegramLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestTelegramLogin(ctx, request.(RequestTelegramLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestTelegramLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RequestTelegramLoginResponseObject); ok {
		if err := validResponse.VisitRequestTelegramLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PollTelegramLogin operation middleware
func (sh *strictHandler) PollTelegramLogin(ctx *gin.Context) {
	var request PollTelegramLoginRequestObject

	var body PollTelegramLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PollTelegramLogin(ctx, request.(PollTelegramLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PollTelegramLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(PollTelegramLoginResponseObject); ok {
		if err := validResponse.VisitPollTelegramLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CommitContent operation middleware
func (sh *strictHandler) CommitContent(ctx *gin.Context) {
	var request CommitContentRequestObject

	var body CommitContentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CommitContent(ctx, request.(CommitContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CommitContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CommitContentResponseObject); ok {
		if err := validResponse.VisitCommitContentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteContent operation middleware
func (sh *strictHandler) DeleteContent(ctx *gin.Context) {
	var request DeleteContentRequestObject

	var body DeleteContentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteContent(ctx, request.(DeleteContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteContentResponseObject); ok {
		if err := validResponse.VisitDeleteContentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetContentFile operation middleware
func (sh *strictHandler) GetContentFile(ctx *gin.Context, params GetContentFileParams) {
	var request GetContentFileRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetContentFile(ctx, request.(GetContentFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContentFile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetContentFileResponseObject); ok {
		if err := validResponse.VisitGetContentFileResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadImage operation middleware
func (sh *strictHandler) UploadImage(ctx *gin.Context) {
	var request UploadImageRequestObject

	var body UploadImageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImage(ctx, request.(UploadImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UploadImageResponseObject); ok {
		if err := validResponse.VisitUploadImageResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveContent operation middleware
func (sh *strictHandler) SaveContent(ctx *gin.Context) {
	var request SaveContentRequestObject

	var body SaveContentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SaveContent(ctx, request.(SaveContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SaveContentResponseObject); ok {
		if err := validResponse.VisitSaveContentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrichTemplate operation middleware
func (sh *strictHandler) EnrichTemplate(ctx *gin.Context) {
	var request EnrichTemplateRequestObject

	var body EnrichTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnrichTemplate(ctx, request.(EnrichTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrichTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(EnrichTemplateResponseObject); ok {
		if err := validResponse.VisitEnrichTemplateResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TranslateContent operation middleware
func (sh *strictHandler) TranslateContent(ctx *gin.Context) {
	var request TranslateContentRequestObject

	var body TranslateContentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TranslateContent(ctx, request.(TranslateContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TranslateContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(TranslateContentResponseObject); ok {
		if err := validResponse.VisitTranslateContentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHello operation middleware
func (sh *strictHandler) GetHello(ctx *gin.Context) {
	var request GetHelloRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHello(ctx, request.(GetHelloRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHello")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHelloResponseObject); ok {
		if err := validResponse.VisitGetHelloResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(ctx *gin.Context) {
	var request ListUsersRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(ctx *gin.Context) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUser operation middleware
func (sh *strictHandler) UpdateUser(ctx *gin.Context, id int64) {
	var request UpdateUserRequestObject

	request.Id = id

	var body UpdateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUser(ctx, request.(UpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateUserResponseObject); ok {
		if err := validResponse.VisitUpdateUserResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
