#!/usr/bin/env node
// Generates the site's "mandala" chapter/review art: a ring of one petal
// motif (<use> + rotate) around a hand-authored center icon, on a dark
// radial-gradient background — see CLAUDE.md > Images > "Guide chapter art
// is hand-authored SVG". Only the frame (gradient, rings, petal ring) is
// generated; the center icon per item stays hand-drawn markup, same as the
// original 11 guide-chapter SVGs (those predate this script and are not
// regenerated by it).
//
// Config lives in SETS below, one named set per content type. Add a new set
// (e.g. "epics") by adding a key — nothing else changes.
//
// Usage:
//   node scripts/generate-mandala.mjs <set> [--only=slug1,slug2]
//   node scripts/generate-mandala.mjs --list

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SIZE = 800
const CENTER = SIZE / 2

function renderMandala({
  bg,
  stroke,
  petalCount,
  centerIcon,
  outerRadius = 330,
  innerRadius = outerRadius - 150,
  rings = [outerRadius + 20, Math.round((outerRadius + innerRadius) / 2 + 15)],
  petalOpacity = 0.4,
  petalStrokeWidth = 1.6,
  ringOpacity = 0.28,
}) {
  const midRadius = (outerRadius + innerRadius) / 2
  // Cap petal half-width to a fraction of the gap between adjacent petals at
  // their widest point, so they read as separate petals instead of overlapping.
  const arcSpacing = 2 * outerRadius * Math.sin(Math.PI / petalCount)
  const halfWidth = Math.round(Math.min(48, Math.max(14, arcSpacing * 0.42)))
  const baseY = Math.round(CENTER - innerRadius)
  const tipY = Math.round(CENTER - outerRadius)
  const midY = (CENTER - midRadius).toFixed(1)
  const petalPath = `M${CENTER},${baseY} Q${CENTER + halfWidth},${midY} ${CENTER},${tipY} Q${CENTER - halfWidth},${midY} ${CENTER},${baseY} Z`

  const petals = Array.from(
    { length: petalCount },
    (_, i) => `  <use href="#petal" transform="rotate(${(360 / petalCount) * i} ${CENTER} ${CENTER})"/>`
  ).join('\n')

  const ringCircles = rings
    .map(
      (r) =>
        `  <circle cx="${CENTER}" cy="${CENTER}" r="${r}" fill="none" stroke="${stroke}" stroke-width="1" opacity="${ringOpacity}"/>`
    )
    .join('\n')

  return `<svg viewBox="0 0 ${SIZE} ${SIZE}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="bg" cx="50%" cy="46%" r="72%">
      <stop offset="0%" stop-color="${bg[0]}"/>
      <stop offset="55%" stop-color="${bg[1]}"/>
      <stop offset="100%" stop-color="${bg[2]}"/>
    </radialGradient>
    <path id="petal" d="${petalPath}" fill="none" stroke="${stroke}" stroke-width="${petalStrokeWidth}" opacity="${petalOpacity}"/>
  </defs>
  <rect width="${SIZE}" height="${SIZE}" fill="url(#bg)"/>
${ringCircles}
${petals}
  <g transform="translate(${CENTER},${CENTER})">
${centerIcon.trim()}
  </g>
</svg>
`
}

const SETS = {
  // The 11 existing chapters (herbalism/homeopathy/founder-guide) predate this
  // script and were hand-authored one-off — they are NOT listed here and this
  // script will never touch them. Add new Compass chapters here as they're
  // written, so future art stays reproducible/tweakable instead of one-off.
  guides: {
    outDir: 'public/images',
    prefix: 'guide',
    items: [
      // «Inside websites like this» (inside-websites) — the engine-room course.
      // Shared cool-blue family, one hue step per chapter, icons per layer.
      {
        slug: 'inside-01-the-whole-machine',
        petalCount: 12,
        bg: ['#123043', '#1f6a8f', '#061019'],
        stroke: '#8fd8f5',
        centerIcon: `
<path d="M0,-64 L64,-32 L0,0 L-64,-32 Z" fill="#bfeaff" opacity="0.9"/>
<path d="M0,-34 L64,-2 L0,30 L-64,-2 Z" fill="#5fb6dd" opacity="0.85"/>
<path d="M0,-4 L64,28 L0,60 L-64,28 Z" fill="#1f6a8f" stroke="#8fd8f5" stroke-width="2" opacity="0.9"/>`,
      },
      {
        slug: 'inside-02-from-markdown-to-bundle',
        petalCount: 10,
        bg: ['#132a3d', '#1e5a7a', '#050f18'],
        stroke: '#8fd0e8',
        centerIcon: `
<rect x="-34" y="-88" width="68" height="52" rx="9" fill="#dff2fb" opacity="0.92"/>
<path d="M-22,-52 L-22,-74 L-12,-62 L-2,-74 L-2,-52" fill="none" stroke="#1e5a7a" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12,-70 L22,-70 M12,-58 L24,-58" stroke="#1e5a7a" stroke-width="4" stroke-linecap="round"/>
<path d="M0,-26 L0,-2 M-11,-13 L0,-2 L11,-13" fill="none" stroke="#8fd0e8" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M0,10 L44,32 L0,54 L-44,32 Z" fill="#9fdcf0" opacity="0.95"/>
<path d="M-44,32 L0,54 L0,90 L-44,68 Z" fill="#4a9cc2" opacity="0.95"/>
<path d="M44,32 L0,54 L0,90 L44,68 Z" fill="#2c6e91" opacity="0.95"/>`,
      },
      {
        slug: 'inside-03-the-living-page',
        petalCount: 14,
        bg: ['#1b2647', '#2f4a8a', '#070b18'],
        stroke: '#a8bef5',
        centerIcon: `
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9"/>
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9" transform="rotate(60)"/>
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9" transform="rotate(-60)"/>
<circle cx="0" cy="0" r="12" fill="#dbe6ff"/>`,
      },
      {
        slug: 'inside-04-shipping-the-box',
        petalCount: 8,
        bg: ['#14343d', '#1f6473', '#05100f'],
        stroke: '#7fd8d8',
        centerIcon: `
<rect x="-70" y="-46" width="140" height="80" rx="8" fill="#d7f2f0" opacity="0.92"/>
<path d="M-46,-46 L-46,34 M-23,-46 L-23,34 M0,-46 L0,34 M23,-46 L23,34 M46,-46 L46,34" stroke="#1f6473" stroke-width="4"/>
<rect x="-70" y="-46" width="140" height="80" rx="8" fill="none" stroke="#1f6473" stroke-width="4"/>
<path d="M-72,58 Q-54,48 -36,58 T0,58 T36,58 T72,58" fill="none" stroke="#7fd8d8" stroke-width="4" stroke-linecap="round"/>
<path d="M-58,76 Q-44,68 -30,76 T-2,76 T26,76 T54,76" fill="none" stroke="#7fd8d8" stroke-width="3" stroke-linecap="round" opacity="0.6"/>`,
      },
      {
        slug: 'inside-05-owning-the-stack',
        petalCount: 16,
        bg: ['#1c2f4a', '#3a5f96', '#0a1120'],
        stroke: '#a8c8f0',
        centerIcon: `
<path d="M-80,72 L-12,-46 L18,-2 L40,-26 L80,72 Z" fill="#dce9fb" opacity="0.92"/>
<path d="M-12,-46 L2,-22 L-6,-14 L8,4 L18,-2 Z" fill="#8fb0dd" opacity="0.8"/>
<path d="M-12,-46 L-12,-88" stroke="#3a5f96" stroke-width="4" stroke-linecap="round"/>
<path d="M-12,-88 L26,-77 L-12,-66 Z" fill="#3a5f96"/>`,
      },

      // «Трофология» / "Trophology" (trophology) — food combining. Warm
      // terracotta/amber family (distinct from homeopathy purple, herbalism
      // green, inside blue, founder gold); one icon per chapter concept.
      {
        // ch. 1 — the stomach's two opposite juices (acid + alkaline drops).
        slug: 'trophology-01-stomach-not-a-blender',
        petalCount: 12,
        bg: ['#3d1f0c', '#7a3f14', '#160a02'],
        stroke: '#f0b36a',
        centerIcon: `
<path d="M-30,-46 C-14,-18 -6,-8 -6,4 A24,24 0 1 1 -54,4 C-54,-8 -46,-18 -30,-46 Z" fill="#e08a4a" opacity="0.92"/>
<path d="M30,-46 C46,-18 54,-8 54,4 A24,24 0 1 1 6,4 C6,-8 14,-18 30,-46 Z" fill="#8fc9c0" opacity="0.9"/>
<path d="M0,-40 L0,40" stroke="#f2dcc0" stroke-width="3" stroke-dasharray="4 5" opacity="0.7"/>`,
      },
      {
        // ch. 2 — the plate split down the middle: protein | starch.
        slug: 'trophology-02-the-master-rule',
        petalCount: 10,
        bg: ['#402008', '#833f0f', '#170902'],
        stroke: '#f2a65a',
        centerIcon: `
<circle cx="0" cy="0" r="72" fill="#f2dcc0" opacity="0.92"/>
<path d="M0,-72 A72,72 0 0 1 0,72 Z" fill="#d98a4a" opacity="0.9"/>
<line x1="0" y1="-72" x2="0" y2="72" stroke="#7a3f14" stroke-width="4"/>
<circle cx="0" cy="0" r="72" fill="none" stroke="#7a3f14" stroke-width="3"/>`,
      },
      {
        // ch. 3 — timing: a clock face with a leaf sprig.
        slug: 'trophology-03-fruit-melons-and-timing',
        petalCount: 14,
        bg: ['#3a2410', '#7a4a1a', '#150c04'],
        stroke: '#f0c070',
        centerIcon: `
<circle cx="0" cy="6" r="62" fill="#f2dcc0" opacity="0.92" stroke="#7a3f14" stroke-width="3"/>
<line x1="0" y1="6" x2="0" y2="-32" stroke="#7a3f14" stroke-width="5" stroke-linecap="round"/>
<line x1="0" y1="6" x2="30" y2="20" stroke="#7a3f14" stroke-width="4" stroke-linecap="round"/>
<circle cx="0" cy="6" r="6" fill="#7a3f14"/>
<path d="M0,-56 C-18,-64 -30,-82 -20,-96 C-4,-88 2,-70 0,-56 Z" fill="#9ec96a" opacity="0.92"/>`,
      },
      {
        // ch. 4 — the combining map: a rounded grid.
        slug: 'trophology-04-the-combining-map',
        petalCount: 8,
        bg: ['#3d1c14', '#7e3822', '#160806'],
        stroke: '#f2a67a',
        centerIcon: `
<rect x="-64" y="-64" width="128" height="128" rx="16" fill="#f2dcc0" opacity="0.92" stroke="#7a3f14" stroke-width="3"/>
<line x1="0" y1="-64" x2="0" y2="64" stroke="#7a3f14" stroke-width="3"/>
<line x1="-64" y1="0" x2="64" y2="0" stroke="#7a3f14" stroke-width="3"/>
<circle cx="-32" cy="-32" r="13" fill="#4f9a86"/>
<circle cx="32" cy="32" r="13" fill="#4f9a86"/>
<path d="M22,-40 L44,-40 M22,-24 L44,-24" stroke="#c65a24" stroke-width="5" stroke-linecap="round"/>
<path d="M-44,24 L-22,24 M-44,40 L-22,40" stroke="#c65a24" stroke-width="5" stroke-linecap="round"/>`,
      },
      {
        // ch. 5 — the real table: a plate with fork and knife.
        slug: 'trophology-05-the-real-table',
        petalCount: 16,
        bg: ['#42230c', '#864614', '#180b03'],
        stroke: '#f4bb70',
        centerIcon: `
<circle cx="0" cy="0" r="52" fill="#f2dcc0" opacity="0.92" stroke="#7a3f14" stroke-width="3"/>
<circle cx="0" cy="0" r="34" fill="none" stroke="#c98a52" stroke-width="2" opacity="0.7"/>
<path d="M-86,-56 L-86,-22 M-78,-56 L-78,-22 M-70,-56 L-70,-22" stroke="#f0d8bc" stroke-width="4" stroke-linecap="round"/>
<path d="M-78,-22 L-78,58" stroke="#f0d8bc" stroke-width="7" stroke-linecap="round"/>
<path d="M78,-56 L78,58" stroke="#f0d8bc" stroke-width="7" stroke-linecap="round"/>
<path d="M78,-56 C92,-48 92,-22 78,-16 Z" fill="#f0d8bc" opacity="0.85"/>`,
      },

      // «Домашний травник» / "The home herbalist" (herbalism), chapters 4–11.
      // Shared deep-green family (the herbalism epic thumbnail uses
      // ['#0f3d2a','#1a6b48','#04140d'] / stroke '#8ff2c9') — one hue/lightness
      // step per chapter, like trophology does with amber. Chapters 1–3 keep
      // their original hand-authored one-off SVGs (not listed here).
      {
        // ch. 4 — the kitchen ten: ten labeled jars in two rows.
        slug: 'herbalism-04-the-kitchen-ten',
        petalCount: 10,
        bg: ['#0f3d2a', '#1a6b48', '#04140d'],
        stroke: '#8ff2c9',
        centerIcon: `
<g fill="#d8f5e6" opacity="0.92">
  <rect x="-84" y="-52" width="28" height="40" rx="6"/><rect x="-48" y="-52" width="28" height="40" rx="6"/>
  <rect x="-12" y="-52" width="28" height="40" rx="6"/><rect x="24" y="-52" width="28" height="40" rx="6"/>
  <rect x="60" y="-52" width="28" height="40" rx="6"/>
  <rect x="-84" y="8" width="28" height="40" rx="6"/><rect x="-48" y="8" width="28" height="40" rx="6"/>
  <rect x="-12" y="8" width="28" height="40" rx="6"/><rect x="24" y="8" width="28" height="40" rx="6"/>
  <rect x="60" y="8" width="28" height="40" rx="6"/>
</g>
<g stroke="#1a6b48" stroke-width="4" stroke-linecap="round">
  <path d="M-82,-56 L-58,-56 M-46,-56 L-22,-56 M-10,-56 L14,-56 M26,-56 L50,-56 M62,-56 L86,-56"/>
  <path d="M-82,4 L-58,4 M-46,4 L-22,4 M-10,4 L14,4 M26,4 L50,4 M62,4 L86,4"/>
</g>`,
      },
      {
        // ch. 5 — alcohol, vinegar, honey: three vessels side by side.
        slug: 'herbalism-05-tinctures-and-oxymels',
        petalCount: 12,
        bg: ['#123a20', '#237a4a', '#05130a'],
        stroke: '#93f0be',
        centerIcon: `
<path d="M-72,60 L-72,-10 Q-72,-26 -60,-30 L-60,-46 L-40,-46 L-40,-30 Q-28,-26 -28,-10 L-28,60 Z" fill="#d8f5e6" opacity="0.92"/>
<rect x="-62" y="-58" width="24" height="12" rx="4" fill="#3fae7a"/>
<path d="M-22,60 L-22,-2 Q-22,-14 -12,-18 L-12,-52 Q-12,-62 -2,-62 Q8,-62 8,-52 L8,-18 Q18,-14 18,-2 L18,60 Z" fill="#a8e8c8" opacity="0.88"/>
<path d="M28,60 L28,6 Q28,-8 40,-12 L40,-24 L64,-24 L64,-12 Q76,-8 76,6 L76,60 Z" fill="#f0d890" opacity="0.9"/>
<path d="M36,-32 L68,-32" stroke="#f0d890" stroke-width="8" stroke-linecap="round" opacity="0.9"/>
<path d="M-72,30 L-28,30 M-22,34 L18,34 M28,36 L76,36" stroke="#1a6b48" stroke-width="4" opacity="0.7"/>`,
      },
      {
        // ch. 6 — skin and touch: an open palm with a falling drop.
        slug: 'herbalism-06-skin-and-touch',
        petalCount: 14,
        bg: ['#0d3d33', '#1a6b5c', '#04120f'],
        stroke: '#8ff2d9',
        centerIcon: `
<path d="M0,-72 C14,-46 24,-32 24,-18 A24,24 0 1 1 -24,-18 C-24,-32 -14,-46 0,-72 Z" fill="#9fe8d0" opacity="0.92"/>
<path d="M-78,38 Q-78,18 -62,18 L54,18 Q74,18 74,38 Q74,62 44,70 L-40,70 Q-78,62 -78,38 Z" fill="#d8f5ec" opacity="0.9"/>
<path d="M-62,18 L-62,-8 M-38,18 L-38,-16 M-14,18 L-14,-20 M10,18 L10,-16" stroke="#d8f5ec" stroke-width="16" stroke-linecap="round" opacity="0.9"/>
<path d="M54,22 Q84,6 78,-14" fill="none" stroke="#d8f5ec" stroke-width="14" stroke-linecap="round" opacity="0.9"/>`,
      },
      {
        // ch. 7 — household protocols: a shield with a leaf at its heart.
        slug: 'herbalism-07-household-protocols',
        petalCount: 8,
        bg: ['#16381c', '#2d6e33', '#071106'],
        stroke: '#a5f0a0',
        centerIcon: `
<path d="M0,-78 C26,-62 52,-56 68,-56 C68,4 52,54 0,80 C-52,54 -68,4 -68,-56 C-52,-56 -26,-62 0,-78 Z" fill="#d8f5dc" opacity="0.92"/>
<path d="M0,-78 C26,-62 52,-56 68,-56 C68,4 52,54 0,80 C-52,54 -68,4 -68,-56 C-52,-56 -26,-62 0,-78 Z" fill="none" stroke="#2d6e33" stroke-width="4"/>
<path d="M0,46 L0,-30" stroke="#2d6e33" stroke-width="5" stroke-linecap="round"/>
<path d="M0,-30 C-28,-34 -38,-58 -24,-74 C-10,-58 -6,-40 0,-30 Z" fill="#57cf74" opacity="0.95"/>
<path d="M0,-14 C28,-18 38,-42 24,-58 C10,-42 6,-24 0,-14 Z" fill="#3fae5a" opacity="0.95"/>
<path d="M-22,14 Q0,34 22,14" fill="none" stroke="#2d6e33" stroke-width="4" stroke-linecap="round" opacity="0.7"/>`,
      },
      {
        // ch. 8 — the harvest year: a four-spoke year wheel with a sprig.
        slug: 'herbalism-08-the-harvest-year',
        petalCount: 16,
        bg: ['#1b3d14', '#3c7a24', '#081204'],
        stroke: '#b8f08f',
        centerIcon: `
<circle cx="0" cy="0" r="70" fill="#e2f5d4" opacity="0.92" stroke="#3c7a24" stroke-width="4"/>
<circle cx="0" cy="0" r="46" fill="none" stroke="#3c7a24" stroke-width="3" opacity="0.7"/>
<path d="M0,-70 L0,70 M-70,0 L70,0" stroke="#3c7a24" stroke-width="4"/>
<circle cx="0" cy="0" r="16" fill="#3c7a24"/>
<path d="M0,-16 C-14,-22 -20,-36 -12,-46 C-2,-38 2,-26 0,-16 Z" fill="#b8f08f"/>`,
      },
      {
        // ch. 9 — the living apothecary: a shelf with three jars on it.
        slug: 'herbalism-09-the-living-apothecary',
        petalCount: 12,
        bg: ['#123527', '#20705a', '#051009'],
        stroke: '#8fe8cc',
        centerIcon: `
<path d="M-84,44 L84,44" stroke="#caa877" stroke-width="8" stroke-linecap="round"/>
<path d="M-72,44 L-72,68 M72,44 L72,68" stroke="#caa877" stroke-width="6" stroke-linecap="round"/>
<rect x="-70" y="-16" width="40" height="60" rx="8" fill="#d8f5ec" opacity="0.92"/>
<path d="M-66,-20 L-34,-20" stroke="#20705a" stroke-width="5" stroke-linecap="round"/>
<rect x="-62" y="2" width="24" height="18" rx="3" fill="#20705a" opacity="0.55"/>
<rect x="-18" y="-40" width="40" height="84" rx="8" fill="#c2f0dc" opacity="0.92"/>
<path d="M-14,-44 L18,-44" stroke="#20705a" stroke-width="5" stroke-linecap="round"/>
<rect x="-10" y="-14" width="24" height="20" rx="3" fill="#20705a" opacity="0.55"/>
<rect x="34" y="-8" width="38" height="52" rx="8" fill="#9fe0c6" opacity="0.92"/>
<path d="M38,-12 L68,-12" stroke="#20705a" stroke-width="5" stroke-linecap="round"/>
<rect x="42" y="8" width="22" height="16" rx="3" fill="#20705a" opacity="0.55"/>`,
      },
      {
        // ch. 10 — the art of the blend: three small circles pouring into one jar.
        slug: 'herbalism-10-formulation',
        petalCount: 10,
        bg: ['#0e3a1e', '#1d7a3f', '#04120a'],
        stroke: '#8ff2a8',
        centerIcon: `
<circle cx="-52" cy="-58" r="20" fill="#57cf94" opacity="0.95"/>
<circle cx="0" cy="-72" r="24" fill="#8ff2a8" opacity="0.95"/>
<circle cx="52" cy="-58" r="20" fill="#3fae7a" opacity="0.95"/>
<path d="M-46,-38 C-36,-22 -18,-12 -8,-8 M0,-46 L0,-10 M46,-38 C36,-22 18,-12 8,-8" fill="none" stroke="#8ff2a8" stroke-width="4" stroke-linecap="round" opacity="0.8"/>
<path d="M-40,0 L-40,14 Q-40,20 -34,22 L-34,64 Q-34,76 -22,76 L22,76 Q34,76 34,64 L34,22 Q40,20 40,14 L40,0 Z" fill="#d8f5e6" opacity="0.92"/>
<path d="M-26,40 L26,40" stroke="#1d7a3f" stroke-width="4" opacity="0.7"/>
<rect x="-14" y="48" width="28" height="18" rx="3" fill="#1d7a3f" opacity="0.55"/>`,
      },
      {
        // ch. 11 — your own path: a winding trail rising to a leaf on the horizon.
        slug: 'herbalism-11-your-own-path',
        petalCount: 14,
        bg: ['#143d2e', '#2a8a64', '#051410'],
        stroke: '#9df5d2',
        centerIcon: `
<path d="M-70,78 C-20,66 40,58 70,42 C30,44 -10,48 -34,40 C6,34 44,24 60,10 C28,14 -4,18 -22,10 C6,2 28,-8 36,-22" fill="none" stroke="#d8f5e6" stroke-width="9" stroke-linecap="round" stroke-linejoin="round" opacity="0.9"/>
<path d="M36,-22 L36,-50" stroke="#9df5d2" stroke-width="4" stroke-linecap="round"/>
<path d="M36,-50 C12,-54 4,-76 18,-90 C32,-78 36,-62 36,-50 Z" fill="#57cf94" opacity="0.95"/>
<path d="M36,-40 C60,-44 68,-64 56,-78 C44,-66 38,-52 36,-40 Z" fill="#8ff2c9" opacity="0.95"/>`,
      },

      // «Может, гомеопатия» / "Maybe Homeopathy" (homeopathy), chapters 4–11.
      // Shared purple/violet family (ch. 1's hand-authored art uses
      // ['#341a5c','#4a1f7a','#0c0618'] / stroke '#c9a8f7') — one hue step per
      // chapter. Chapters 1–3 keep their original hand-authored one-off SVGs.
      {
        // ch. 4 — the first ten: a 2×5 grid of vial dots inside the kit box.
        slug: 'homeopathy-04-first-ten-remedies',
        petalCount: 10,
        bg: ['#341a5c', '#4a1f7a', '#0c0618'],
        stroke: '#c9a8f7',
        centerIcon: `
<rect x="-78" y="-56" width="156" height="112" rx="14" fill="none" stroke="#c9a8f7" stroke-width="4"/>
<g fill="#e6cdf7" opacity="0.92">
  <circle cx="-56" cy="-24" r="12"/><circle cx="-28" cy="-24" r="12"/><circle cx="0" cy="-24" r="12"/><circle cx="28" cy="-24" r="12"/><circle cx="56" cy="-24" r="12"/>
  <circle cx="-56" cy="24" r="12"/><circle cx="-28" cy="24" r="12"/><circle cx="0" cy="24" r="12"/><circle cx="28" cy="24" r="12"/><circle cx="56" cy="24" r="12"/>
</g>`,
      },
      {
        // ch. 5 — matching the picture: two overlapping circles (a venn —
        // the remedy's picture meeting the patient's).
        slug: 'homeopathy-05-matching-the-picture',
        petalCount: 12,
        bg: ['#2f1650', '#55238a', '#0b0616'],
        stroke: '#cbaaf5',
        centerIcon: `
<circle cx="-26" cy="0" r="56" fill="#a06de0" opacity="0.5"/>
<circle cx="26" cy="0" r="56" fill="#e6cdf7" opacity="0.5"/>
<circle cx="-26" cy="0" r="56" fill="none" stroke="#cbaaf5" stroke-width="4"/>
<circle cx="26" cy="0" r="56" fill="none" stroke="#cbaaf5" stroke-width="4"/>`,
      },
      {
        // ch. 6 — acute care at home: a house outline with a crescent moon
        // (the night watch).
        slug: 'homeopathy-06-acute-care-at-home',
        petalCount: 8,
        bg: ['#38175a', '#5c2a86', '#0d0718'],
        stroke: '#d4b2f7',
        centerIcon: `
<path d="M-58,10 L0,-44 L58,10 L58,66 L-58,66 Z" fill="none" stroke="#d4b2f7" stroke-width="5" stroke-linejoin="round"/>
<path d="M-14,66 L-14,28 L14,28 L14,66" fill="none" stroke="#d4b2f7" stroke-width="4" stroke-linejoin="round"/>
<g transform="translate(46,-56)"><path d="M0,-34 A26,26 0 1 0 0,18 A32,32 0 0 1 0,-34 Z" fill="#e6cdf7" opacity="0.92"/></g>`,
      },
      {
        // ch. 7 — watch and wait: an hourglass.
        slug: 'homeopathy-07-watch-and-wait',
        petalCount: 14,
        bg: ['#2c1a54', '#472a8a', '#0a0716'],
        stroke: '#b8a8f5',
        centerIcon: `
<path d="M-40,-64 L40,-64 L40,-48 C40,-24 12,-12 12,0 C12,12 40,24 40,48 L40,64 L-40,64 L-40,48 C-40,24 -12,12 -12,0 C-12,-12 -40,-24 -40,-48 Z" fill="none" stroke="#b8a8f5" stroke-width="5" stroke-linejoin="round"/>
<path d="M-46,-70 L46,-70 M-46,70 L46,70" stroke="#b8a8f5" stroke-width="7" stroke-linecap="round"/>
<path d="M-22,-48 L22,-48 L2,-16 L-2,-16 Z" fill="#e6cdf7" opacity="0.9"/>
<path d="M-26,56 L26,56 L0,28 Z" fill="#e6cdf7" opacity="0.9"/>
<line x1="0" y1="-14" x2="0" y2="26" stroke="#e6cdf7" stroke-width="3" stroke-dasharray="2 6"/>`,
      },
      {
        // ch. 8 — the terrain: layered soil strata with a sprout on top.
        slug: 'homeopathy-08-terrain-before-remedy',
        petalCount: 16,
        bg: ['#3a1548', '#61227a', '#100617'],
        stroke: '#dfa8f0',
        centerIcon: `
<g stroke-linecap="round">
  <path d="M-70,10 L70,10" stroke="#dfa8f0" stroke-width="10" opacity="0.95"/>
  <path d="M-66,34 L66,34" stroke="#b06ad0" stroke-width="10" opacity="0.85"/>
  <path d="M-60,58 L60,58" stroke="#8a4aa8" stroke-width="10" opacity="0.8"/>
  <path d="M-52,82 L52,82" stroke="#6b3585" stroke-width="10" opacity="0.75"/>
</g>
<path d="M0,4 L0,-38" stroke="#dfa8f0" stroke-width="5" stroke-linecap="round"/>
<path d="M0,-38 C-22,-42 -30,-62 -18,-76 C-6,-64 -2,-50 0,-38 Z" fill="#e6cdf7" opacity="0.95"/>
<path d="M0,-30 C22,-34 30,-54 18,-68 C6,-56 2,-42 0,-30 Z" fill="#c98ae8" opacity="0.95"/>`,
      },
      {
        // ch. 9 — the family system: a ring of small dots around a hearth-like
        // flame at the center.
        slug: 'homeopathy-09-the-family-system',
        petalCount: 12,
        bg: ['#33184f', '#532687', '#0c0714'],
        stroke: '#c9a8f0',
        centerIcon: `
<g fill="#c9a8f0" opacity="0.9">
  <circle cx="64" cy="0" r="9"/><circle cx="45.3" cy="45.3" r="9"/><circle cx="0" cy="64" r="9"/><circle cx="-45.3" cy="45.3" r="9"/>
  <circle cx="-64" cy="0" r="9"/><circle cx="-45.3" cy="-45.3" r="9"/><circle cx="0" cy="-64" r="9"/><circle cx="45.3" cy="-45.3" r="9"/>
</g>
<path d="M0,-34 C10,-20 20,-10 20,2 A20,20 0 1 1 -20,2 C-20,-10 -10,-20 0,-34 Z" fill="#e6cdf7" opacity="0.95"/>
<path d="M0,-12 C5,-5 9,0 9,7 A9,9 0 1 1 -9,7 C-9,0 -5,-5 0,-12 Z" fill="#532687" opacity="0.9"/>
<path d="M-26,28 L26,28" stroke="#c9a8f0" stroke-width="6" stroke-linecap="round"/>`,
      },
      {
        // ch. 10 — messy cases: a tangled thread resolving into a straight line.
        slug: 'homeopathy-10-messy-cases',
        petalCount: 10,
        bg: ['#2e155c', '#4b2394', '#090612'],
        stroke: '#b9a5f7',
        centerIcon: `
<path d="M-84,0 C-70,-34 -52,30 -36,-6 C-24,-32 -18,26 -4,10 C4,0 -12,-18 2,-22 C16,-26 12,2 24,4 C40,6 56,4 84,4" fill="none" stroke="#e6cdf7" stroke-width="5" stroke-linecap="round"/>
<circle cx="84" cy="4" r="7" fill="#b9a5f7"/>`,
      },
      {
        // ch. 11 — learning the rest yourself: an open book with a path
        // rising from it.
        slug: 'homeopathy-11-learning-the-rest',
        petalCount: 14,
        bg: ['#3c1a52', '#66307e', '#100818'],
        stroke: '#e0b5f2',
        centerIcon: `
<path d="M-76,30 C-50,18 -24,18 0,30 C24,18 50,18 76,30 L76,46 C50,34 24,34 0,46 C-24,34 -50,34 -76,46 Z" fill="#e6cdf7" opacity="0.92"/>
<path d="M0,30 L0,46" stroke="#66307e" stroke-width="3"/>
<path d="M0,26 C-8,2 10,-14 -2,-36 C-10,-52 6,-64 2,-78" fill="none" stroke="#e0b5f2" stroke-width="5" stroke-linecap="round"/>
<circle cx="2" cy="-84" r="6" fill="#e6cdf7"/>`,
      },
    ],
  },

  // Thumbnails for the epic strip at the top of /guides (site.yaml `epics:`).
  // One per course, icon representing the course as a whole rather than any
  // single chapter — kept visually distinct from that course's own chapter
  // icons (see CLAUDE.md > Images for what each chapter already uses).
  epics: {
    outDir: 'public/images',
    prefix: 'epic',
    items: [
      {
        slug: 'founder-guide',
        petalCount: 10,
        bg: ['#4a3005', '#8a5c10', '#180f02'],
        stroke: '#ffd77a',
        centerIcon: `
<ellipse cx="0" cy="72" rx="46" ry="10" fill="#8a5c10" opacity="0.5"/>
<path d="M0,10 C-45,10 -55,-35 -30,-55 C-10,-35 -15,10 0,10 Z" fill="#ffe9b0" opacity="0.92"/>
<path d="M0,-10 C45,-10 55,-55 30,-75 C10,-55 15,-10 0,-10 Z" fill="#f4c542" opacity="0.92"/>
<path d="M0,70 L0,-20" fill="none" stroke="#ffd77a" stroke-width="4" stroke-linecap="round"/>`,
      },
      {
        slug: 'homeopathy',
        petalCount: 14,
        bg: ['#3d1550', '#6b2590', '#120818'],
        stroke: '#e0aaf7',
        centerIcon: `
<path d="M-30,90 L-30,-20 Q-30,-55 -12,-62 L-12,-80 Q-12,-92 0,-92 Q12,-92 12,-80 L12,-62 Q30,-55 30,-20 L30,90 Z"
      fill="#e6cdf7" opacity="0.92"/>
<rect x="-22" y="10" width="44" height="50" rx="6" fill="#3d1550" opacity="0.85"/>
<path d="M-11,35 L11,35 M0,24 L0,46" fill="none" stroke="#e6cdf7" stroke-width="5" stroke-linecap="round"/>`,
      },
      {
        slug: 'herbalism',
        petalCount: 12,
        bg: ['#0f3d2a', '#1a6b48', '#04140d'],
        stroke: '#8ff2c9',
        centerIcon: `
<ellipse cx="0" cy="80" rx="50" ry="8" fill="#0f3d2a" opacity="0.6"/>
<path d="M0,80 Q-25,95 -42,115 M0,80 Q10,98 5,120 M0,80 Q25,92 30,112" fill="none" stroke="#caa877" stroke-width="3" opacity="0.7"/>
<path d="M0,80 L0,-10" fill="none" stroke="#8ff2c9" stroke-width="4" stroke-linecap="round"/>
<path d="M0,-10 C-40,-15 -55,-50 -35,-75 C-15,-55 -10,-20 0,-10 Z" fill="#3fae7a" opacity="0.9"/>
<path d="M0,10 C40,5 55,-30 35,-55 C15,-35 10,0 0,10 Z" fill="#57cf94" opacity="0.9"/>
<path d="M0,30 C-30,35 -42,55 -28,72 C-14,58 -8,40 0,30 Z" fill="#3fae7a" opacity="0.85"/>`,
      },
      {
        // «Inside websites like this» — browser window + code brackets,
        // distinct from the course's own layered/atom/container chapter icons.
        slug: 'inside-websites',
        petalCount: 12,
        bg: ['#0d2f45', '#1a5f7a', '#04121c'],
        stroke: '#7fd4f2',
        centerIcon: `
<rect x="-70" y="-52" width="140" height="104" rx="12" fill="#0d2f45" stroke="#7fd4f2" stroke-width="3" opacity="0.95"/>
<line x1="-70" y1="-28" x2="70" y2="-28" stroke="#7fd4f2" stroke-width="2.5"/>
<circle cx="-54" cy="-40" r="4" fill="#7fd4f2"/>
<circle cx="-40" cy="-40" r="4" fill="#7fd4f2" opacity="0.7"/>
<circle cx="-26" cy="-40" r="4" fill="#7fd4f2" opacity="0.45"/>
<path d="M-34,-8 L-52,8 L-34,24" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M34,-8 L52,8 L34,24" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<line x1="10" y1="-12" x2="-10" y2="28" stroke="#bfeaff" stroke-width="5" stroke-linecap="round"/>`,
      },
      {
        // «Трофология» — a yin-yang made warm (the Taoist balance of foods),
        // distinct from the course's own plate/clock/grid chapter icons.
        slug: 'trophology',
        petalCount: 14,
        bg: ['#3a1d0a', '#8a4614', '#140902'],
        stroke: '#f0b36a',
        centerIcon: `
<circle cx="0" cy="0" r="80" fill="#f2dcc0" opacity="0.95"/>
<path d="M0,-80 A80,80 0 0 1 0,80 A40,40 0 0 1 0,0 A40,40 0 0 0 0,-80 Z" fill="#b04e1e"/>
<circle cx="0" cy="-40" r="13" fill="#f2dcc0"/>
<circle cx="0" cy="40" r="13" fill="#b04e1e"/>
<circle cx="0" cy="0" r="80" fill="none" stroke="#f0b36a" stroke-width="3" opacity="0.85"/>`,
      },
    ],
  },

  reviews: {
    outDir: 'public/images',
    prefix: 'review',
    items: [
      {
        slug: 'beeswax-food-wraps',
        petalCount: 12,
        bg: ['#3a2408', '#6b4a12', '#140d02'],
        stroke: '#f4c542',
        centerIcon: `
<polygon points="0,-70 61,-35 61,35 0,70 -61,35 -61,-35" fill="#f4c542" opacity="0.92"/>
<polygon points="0,-70 61,-35 61,35 0,70 -61,35 -61,-35" fill="none" stroke="#7a4a06" stroke-width="3" opacity="0.6"/>
<path d="M0,-70 L0,70 M-61,-35 L61,35 M61,-35 L-61,35" stroke="#c98a12" stroke-width="1.6" opacity="0.5"/>`,
      },
      {
        slug: 'castile-soap',
        petalCount: 8,
        bg: ['#1a3a26', '#2c6b3f', '#081208'],
        stroke: '#8fe0a8',
        centerIcon: `
<rect x="-34" y="-20" width="68" height="120" rx="18" fill="#eaf7e8" opacity="0.92"/>
<rect x="-10" y="-70" width="20" height="55" rx="6" fill="#bfe6bb"/>
<rect x="-16" y="-84" width="32" height="16" rx="6" fill="#7fb86a"/>
<circle cx="0" cy="30" r="16" fill="none" stroke="#5c8f4e" stroke-width="2.4" opacity="0.7"/>`,
      },
      {
        slug: 'glass-baby-bottles',
        petalCount: 10,
        bg: ['#0d3140', '#155c78', '#04141c'],
        stroke: '#7fd8f0',
        centerIcon: `
<path d="M-28,90 L-28,-10 Q-28,-45 -10,-55 L-10,-70 Q-10,-82 0,-82 Q10,-82 10,-70 L10,-55 Q28,-45 28,-10 L28,90 Z"
      fill="#dff3fb" opacity="0.9" stroke="#8fd0e8" stroke-width="2"/>
<path d="M-28,10 L28,10 M-28,35 L28,35 M-28,60 L28,60" stroke="#8fd0e8" stroke-width="2" opacity="0.6" fill="none"/>
<ellipse cx="0" cy="-88" rx="9" ry="7" fill="#f6c9a0"/>`,
      },
      {
        slug: 'organic-cotton-swaddle',
        petalCount: 14,
        bg: ['#3a1c28', '#6b2f47', '#170810'],
        stroke: '#f5b8cf',
        centerIcon: `
<rect x="-70" y="-50" width="140" height="100" rx="14" fill="#fbeee7" opacity="0.85"/>
<path d="M-70,-50 L0,10 L70,-50" fill="none" stroke="#f3ded5" stroke-width="2.4" opacity="0.7"/>
<path d="M-70,50 L0,-5 L70,50" fill="none" stroke="#f3ded5" stroke-width="2.4" opacity="0.5"/>`,
      },
      {
        slug: 'stainless-food-container',
        petalCount: 8,
        bg: ['#22303a', '#3d5566', '#0a1014'],
        stroke: '#b9d4e3',
        centerIcon: `
<rect x="-75" y="-50" width="150" height="100" rx="16" fill="#e7f1f7" opacity="0.88" stroke="#9db9c8" stroke-width="2"/>
<line x1="-10" y1="-50" x2="-10" y2="50" stroke="#9db9c8" stroke-width="2.2"/>
<line x1="-75" y1="0" x2="-10" y2="0" stroke="#9db9c8" stroke-width="2.2"/>`,
      },
      {
        slug: 'wool-sleep-sack',
        petalCount: 16,
        bg: ['#3a2010', '#7a4420', '#170c05'],
        stroke: '#f2b98a',
        centerIcon: `
<g fill="#f5e6d8" opacity="0.92">
  <circle cx="-40" cy="-10" r="34"/>
  <circle cx="0" cy="-35" r="38"/>
  <circle cx="42" cy="-10" r="34"/>
  <circle cx="-25" cy="25" r="30"/>
  <circle cx="25" cy="25" r="30"/>
  <circle cx="0" cy="5" r="28"/>
</g>
<path d="M-15,-5 q8,10 0,20 M15,-5 q-8,10 0,20" fill="none" stroke="#caa27e" stroke-width="2" opacity="0.5"/>`,
      },
    ],
  },
}

function main() {
  const [, , setName, ...rest] = process.argv

  if (!setName || setName === '--list') {
    console.log(`Available sets: ${Object.keys(SETS).join(', ')}`)
    for (const [name, set] of Object.entries(SETS)) {
      console.log(`  ${name}: ${set.items.length} item(s) -> ${set.outDir}/${set.prefix}-<slug>.svg`)
    }
    return
  }

  const set = SETS[setName]
  if (!set) {
    console.error(`Unknown set "${setName}". Available: ${Object.keys(SETS).join(', ')}`)
    process.exit(1)
  }

  const onlyArg = rest.find((a) => a.startsWith('--only='))
  const only = onlyArg ? new Set(onlyArg.slice('--only='.length).split(',')) : null

  const outDir = join(ROOT, set.outDir)
  mkdirSync(outDir, { recursive: true })

  let written = 0
  for (const item of set.items) {
    if (only && !only.has(item.slug)) continue
    const svg = renderMandala(item)
    const file = join(outDir, `${set.prefix}-${item.slug}.svg`)
    writeFileSync(file, svg)
    console.log(`wrote ${file}`)
    written++
  }
  if (written === 0) console.log(`Nothing written (set "${setName}" has no matching items).`)
}

main()
