#!/usr/bin/env bash
# Manual, owner-invoked backend release to the VM (via `task be:deploy`).
# Temporary flow until doco-cd GitOps takes over (deploy/README.md). It:
#   1. resolves the image tag from the latest successful "Build backend image"
#      CI run (or an explicit BE_TAG=…),
#   2. assembles deploy.env = VM-specific non-secrets + BE_TAG + the secrets
#      mirrored in the repo-root .env,
#   3. scps compose.yaml + Caddyfile + deploy.env to the VM,
#   4. pulls the image and recreates the container.
# Secrets live only in the local .env and the VM's deploy.env — never the repo.
set -euo pipefail

: "${VM_SSH:?}" "${VM_KEY:?}" "${VM_DIR:?}" "${API_DOMAIN:?}" "${CORS_ORIGINS:?}"
ROOT_ENV="${ROOT_ENV:-.env}"
WORKFLOW="${BE_WORKFLOW:-Build backend image}"
VM_KEY="${VM_KEY/#\~/$HOME}" # ssh -i won't expand ~ inside a quoted var
VM_PORT="${VM_PORT:-13337}"  # SSH moved off 22; see deploy/infra-log.md

# 1. Image tag — explicit override, else the newest green CI build on main.
if [ -n "${BE_TAG:-}" ]; then
  tag="$BE_TAG"
  echo "→ image tag (pinned): $tag"
else
  read -r sha title < <(gh run list --workflow "$WORKFLOW" --branch main \
    --status success --limit 1 --json headSha,displayTitle \
    -q '.[0] | "\(.headSha) \(.displayTitle)"')
  [ -n "${sha:-}" ] || { echo "no successful '$WORKFLOW' run found on main"; exit 1; }
  tag="sha-$sha"
  echo "→ image tag: $tag  ($title)"
  # Warn if a newer main commit exists but its image isn't built yet.
  head="$(git rev-parse origin/main 2>/dev/null || true)"
  [ -n "$head" ] && [ "$head" != "$sha" ] &&
    echo "  ! origin/main is $head — newer than this image; its build may still be running"
fi

# 2. Secrets source.
[ -f "$ROOT_ENV" ] || { echo "missing $ROOT_ENV (the secrets mirror)"; exit 1; }

# 3. Assemble deploy.env: managed non-secrets first, then the .env secrets
#    (comments/blanks and any duplicate managed keys stripped).
env_file="$(mktemp)"
trap 'rm -f "$env_file"' EXIT
{
  echo "# Generated by 'task be:deploy' — overwritten each release, do not hand-edit on the VM."
  echo "API_DOMAIN=$API_DOMAIN"
  echo "CORS_ORIGINS=$CORS_ORIGINS"
  echo "BE_TAG=$tag"
  grep -vE '^[[:space:]]*(#|$)' "$ROOT_ENV" | grep -vE '^(API_DOMAIN|CORS_ORIGINS|BE_TAG)='
} >"$env_file"

# 4. Ship + recreate.
compose="docker compose --env-file deploy.env -f compose.yaml"
ssh -i "$VM_KEY" -p "$VM_PORT" "$VM_SSH" "mkdir -p '$VM_DIR'"
scp -i "$VM_KEY" -P "$VM_PORT" deploy/compose.yaml deploy/Caddyfile "$VM_SSH:$VM_DIR/"
scp -i "$VM_KEY" -P "$VM_PORT" "$env_file" "$VM_SSH:$VM_DIR/deploy.env"
ssh -i "$VM_KEY" -p "$VM_PORT" "$VM_SSH" \
  "cd '$VM_DIR' && chmod 600 deploy.env && $compose pull && $compose up -d && $compose ps"

echo "✓ released $tag to $VM_SSH"
