#!/usr/bin/env node
// Generates the site's "mandala" chapter/review art: a ring of one petal
// motif (<use> + rotate) around a hand-authored center icon, on a dark
// radial-gradient background — see CLAUDE.md > Images > "Guide chapter art
// is hand-authored SVG". Only the frame (gradient, rings, petal ring) is
// generated; the center icon per item stays hand-drawn markup, same as the
// original 11 guide-chapter SVGs (those predate this script and are not
// regenerated by it).
//
// Config lives in SETS below, one named set per content type. Add a new set
// (e.g. "epics") by adding a key — nothing else changes.
//
// Usage:
//   node scripts/generate-mandala.mjs <set> [--only=slug1,slug2]
//   node scripts/generate-mandala.mjs --list

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SIZE = 800
const CENTER = SIZE / 2

function renderMandala({
  bg,
  stroke,
  petalCount,
  centerIcon,
  outerRadius = 330,
  innerRadius = outerRadius - 150,
  rings = [outerRadius + 20, Math.round((outerRadius + innerRadius) / 2 + 15)],
  petalOpacity = 0.4,
  petalStrokeWidth = 1.6,
  ringOpacity = 0.28,
}) {
  const midRadius = (outerRadius + innerRadius) / 2
  // Cap petal half-width to a fraction of the gap between adjacent petals at
  // their widest point, so they read as separate petals instead of overlapping.
  const arcSpacing = 2 * outerRadius * Math.sin(Math.PI / petalCount)
  const halfWidth = Math.round(Math.min(48, Math.max(14, arcSpacing * 0.42)))
  const baseY = Math.round(CENTER - innerRadius)
  const tipY = Math.round(CENTER - outerRadius)
  const midY = (CENTER - midRadius).toFixed(1)
  const petalPath = `M${CENTER},${baseY} Q${CENTER + halfWidth},${midY} ${CENTER},${tipY} Q${CENTER - halfWidth},${midY} ${CENTER},${baseY} Z`

  const petals = Array.from(
    { length: petalCount },
    (_, i) => `  <use href="#petal" transform="rotate(${(360 / petalCount) * i} ${CENTER} ${CENTER})"/>`
  ).join('\n')

  const ringCircles = rings
    .map(
      (r) =>
        `  <circle cx="${CENTER}" cy="${CENTER}" r="${r}" fill="none" stroke="${stroke}" stroke-width="1" opacity="${ringOpacity}"/>`
    )
    .join('\n')

  return `<svg viewBox="0 0 ${SIZE} ${SIZE}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="bg" cx="50%" cy="46%" r="72%">
      <stop offset="0%" stop-color="${bg[0]}"/>
      <stop offset="55%" stop-color="${bg[1]}"/>
      <stop offset="100%" stop-color="${bg[2]}"/>
    </radialGradient>
    <path id="petal" d="${petalPath}" fill="none" stroke="${stroke}" stroke-width="${petalStrokeWidth}" opacity="${petalOpacity}"/>
  </defs>
  <rect width="${SIZE}" height="${SIZE}" fill="url(#bg)"/>
${ringCircles}
${petals}
  <g transform="translate(${CENTER},${CENTER})">
${centerIcon.trim()}
  </g>
</svg>
`
}

const SETS = {
  // The 11 existing chapters (herbalism/homeopathy/founder-guide) predate this
  // script and were hand-authored one-off — they are NOT listed here and this
  // script will never touch them. Add new Compass chapters here as they're
  // written, so future art stays reproducible/tweakable instead of one-off.
  guides: {
    outDir: 'public/images',
    prefix: 'guide',
    items: [
      // «Inside websites like this» (inside-websites) — the engine-room course.
      // Shared cool-blue family, one hue step per chapter, icons per layer.
      {
        slug: 'inside-01-the-whole-machine',
        petalCount: 12,
        bg: ['#123043', '#1f6a8f', '#061019'],
        stroke: '#8fd8f5',
        centerIcon: `
<path d="M0,-64 L64,-32 L0,0 L-64,-32 Z" fill="#bfeaff" opacity="0.9"/>
<path d="M0,-34 L64,-2 L0,30 L-64,-2 Z" fill="#5fb6dd" opacity="0.85"/>
<path d="M0,-4 L64,28 L0,60 L-64,28 Z" fill="#1f6a8f" stroke="#8fd8f5" stroke-width="2" opacity="0.9"/>`,
      },
      {
        slug: 'inside-02-from-markdown-to-bundle',
        petalCount: 10,
        bg: ['#132a3d', '#1e5a7a', '#050f18'],
        stroke: '#8fd0e8',
        centerIcon: `
<rect x="-34" y="-88" width="68" height="52" rx="9" fill="#dff2fb" opacity="0.92"/>
<path d="M-22,-52 L-22,-74 L-12,-62 L-2,-74 L-2,-52" fill="none" stroke="#1e5a7a" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12,-70 L22,-70 M12,-58 L24,-58" stroke="#1e5a7a" stroke-width="4" stroke-linecap="round"/>
<path d="M0,-26 L0,-2 M-11,-13 L0,-2 L11,-13" fill="none" stroke="#8fd0e8" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M0,10 L44,32 L0,54 L-44,32 Z" fill="#9fdcf0" opacity="0.95"/>
<path d="M-44,32 L0,54 L0,90 L-44,68 Z" fill="#4a9cc2" opacity="0.95"/>
<path d="M44,32 L0,54 L0,90 L44,68 Z" fill="#2c6e91" opacity="0.95"/>`,
      },
      {
        slug: 'inside-03-the-living-page',
        petalCount: 14,
        bg: ['#1b2647', '#2f4a8a', '#070b18'],
        stroke: '#a8bef5',
        centerIcon: `
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9"/>
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9" transform="rotate(60)"/>
<ellipse cx="0" cy="0" rx="78" ry="30" fill="none" stroke="#a8bef5" stroke-width="4" opacity="0.9" transform="rotate(-60)"/>
<circle cx="0" cy="0" r="12" fill="#dbe6ff"/>`,
      },
      {
        slug: 'inside-04-shipping-the-box',
        petalCount: 8,
        bg: ['#14343d', '#1f6473', '#05100f'],
        stroke: '#7fd8d8',
        centerIcon: `
<rect x="-70" y="-46" width="140" height="80" rx="8" fill="#d7f2f0" opacity="0.92"/>
<path d="M-46,-46 L-46,34 M-23,-46 L-23,34 M0,-46 L0,34 M23,-46 L23,34 M46,-46 L46,34" stroke="#1f6473" stroke-width="4"/>
<rect x="-70" y="-46" width="140" height="80" rx="8" fill="none" stroke="#1f6473" stroke-width="4"/>
<path d="M-72,58 Q-54,48 -36,58 T0,58 T36,58 T72,58" fill="none" stroke="#7fd8d8" stroke-width="4" stroke-linecap="round"/>
<path d="M-58,76 Q-44,68 -30,76 T-2,76 T26,76 T54,76" fill="none" stroke="#7fd8d8" stroke-width="3" stroke-linecap="round" opacity="0.6"/>`,
      },
      {
        slug: 'inside-05-owning-the-stack',
        petalCount: 16,
        bg: ['#1c2f4a', '#3a5f96', '#0a1120'],
        stroke: '#a8c8f0',
        centerIcon: `
<path d="M-80,72 L-12,-46 L18,-2 L40,-26 L80,72 Z" fill="#dce9fb" opacity="0.92"/>
<path d="M-12,-46 L2,-22 L-6,-14 L8,4 L18,-2 Z" fill="#8fb0dd" opacity="0.8"/>
<path d="M-12,-46 L-12,-88" stroke="#3a5f96" stroke-width="4" stroke-linecap="round"/>
<path d="M-12,-88 L26,-77 L-12,-66 Z" fill="#3a5f96"/>`,
      },
    ],
  },

  // Thumbnails for the epic strip at the top of /guides (site.yaml `epics:`).
  // One per course, icon representing the course as a whole rather than any
  // single chapter — kept visually distinct from that course's own chapter
  // icons (see CLAUDE.md > Images for what each chapter already uses).
  epics: {
    outDir: 'public/images',
    prefix: 'epic',
    items: [
      {
        slug: 'founder-guide',
        petalCount: 10,
        bg: ['#4a3005', '#8a5c10', '#180f02'],
        stroke: '#ffd77a',
        centerIcon: `
<ellipse cx="0" cy="72" rx="46" ry="10" fill="#8a5c10" opacity="0.5"/>
<path d="M0,10 C-45,10 -55,-35 -30,-55 C-10,-35 -15,10 0,10 Z" fill="#ffe9b0" opacity="0.92"/>
<path d="M0,-10 C45,-10 55,-55 30,-75 C10,-55 15,-10 0,-10 Z" fill="#f4c542" opacity="0.92"/>
<path d="M0,70 L0,-20" fill="none" stroke="#ffd77a" stroke-width="4" stroke-linecap="round"/>`,
      },
      {
        slug: 'homeopathy',
        petalCount: 14,
        bg: ['#3d1550', '#6b2590', '#120818'],
        stroke: '#e0aaf7',
        centerIcon: `
<path d="M-30,90 L-30,-20 Q-30,-55 -12,-62 L-12,-80 Q-12,-92 0,-92 Q12,-92 12,-80 L12,-62 Q30,-55 30,-20 L30,90 Z"
      fill="#e6cdf7" opacity="0.92"/>
<rect x="-22" y="10" width="44" height="50" rx="6" fill="#3d1550" opacity="0.85"/>
<path d="M-11,35 L11,35 M0,24 L0,46" fill="none" stroke="#e6cdf7" stroke-width="5" stroke-linecap="round"/>`,
      },
      {
        slug: 'herbalism',
        petalCount: 12,
        bg: ['#0f3d2a', '#1a6b48', '#04140d'],
        stroke: '#8ff2c9',
        centerIcon: `
<ellipse cx="0" cy="80" rx="50" ry="8" fill="#0f3d2a" opacity="0.6"/>
<path d="M0,80 Q-25,95 -42,115 M0,80 Q10,98 5,120 M0,80 Q25,92 30,112" fill="none" stroke="#caa877" stroke-width="3" opacity="0.7"/>
<path d="M0,80 L0,-10" fill="none" stroke="#8ff2c9" stroke-width="4" stroke-linecap="round"/>
<path d="M0,-10 C-40,-15 -55,-50 -35,-75 C-15,-55 -10,-20 0,-10 Z" fill="#3fae7a" opacity="0.9"/>
<path d="M0,10 C40,5 55,-30 35,-55 C15,-35 10,0 0,10 Z" fill="#57cf94" opacity="0.9"/>
<path d="M0,30 C-30,35 -42,55 -28,72 C-14,58 -8,40 0,30 Z" fill="#3fae7a" opacity="0.85"/>`,
      },
      {
        // «Inside websites like this» — browser window + code brackets,
        // distinct from the course's own layered/atom/container chapter icons.
        slug: 'inside-websites',
        petalCount: 12,
        bg: ['#0d2f45', '#1a5f7a', '#04121c'],
        stroke: '#7fd4f2',
        centerIcon: `
<rect x="-70" y="-52" width="140" height="104" rx="12" fill="#0d2f45" stroke="#7fd4f2" stroke-width="3" opacity="0.95"/>
<line x1="-70" y1="-28" x2="70" y2="-28" stroke="#7fd4f2" stroke-width="2.5"/>
<circle cx="-54" cy="-40" r="4" fill="#7fd4f2"/>
<circle cx="-40" cy="-40" r="4" fill="#7fd4f2" opacity="0.7"/>
<circle cx="-26" cy="-40" r="4" fill="#7fd4f2" opacity="0.45"/>
<path d="M-34,-8 L-52,8 L-34,24" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M34,-8 L52,8 L34,24" fill="none" stroke="#bfeaff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
<line x1="10" y1="-12" x2="-10" y2="28" stroke="#bfeaff" stroke-width="5" stroke-linecap="round"/>`,
      },
    ],
  },

  reviews: {
    outDir: 'public/images',
    prefix: 'review',
    items: [
      {
        slug: 'beeswax-food-wraps',
        petalCount: 12,
        bg: ['#3a2408', '#6b4a12', '#140d02'],
        stroke: '#f4c542',
        centerIcon: `
<polygon points="0,-70 61,-35 61,35 0,70 -61,35 -61,-35" fill="#f4c542" opacity="0.92"/>
<polygon points="0,-70 61,-35 61,35 0,70 -61,35 -61,-35" fill="none" stroke="#7a4a06" stroke-width="3" opacity="0.6"/>
<path d="M0,-70 L0,70 M-61,-35 L61,35 M61,-35 L-61,35" stroke="#c98a12" stroke-width="1.6" opacity="0.5"/>`,
      },
      {
        slug: 'castile-soap',
        petalCount: 8,
        bg: ['#1a3a26', '#2c6b3f', '#081208'],
        stroke: '#8fe0a8',
        centerIcon: `
<rect x="-34" y="-20" width="68" height="120" rx="18" fill="#eaf7e8" opacity="0.92"/>
<rect x="-10" y="-70" width="20" height="55" rx="6" fill="#bfe6bb"/>
<rect x="-16" y="-84" width="32" height="16" rx="6" fill="#7fb86a"/>
<circle cx="0" cy="30" r="16" fill="none" stroke="#5c8f4e" stroke-width="2.4" opacity="0.7"/>`,
      },
      {
        slug: 'glass-baby-bottles',
        petalCount: 10,
        bg: ['#0d3140', '#155c78', '#04141c'],
        stroke: '#7fd8f0',
        centerIcon: `
<path d="M-28,90 L-28,-10 Q-28,-45 -10,-55 L-10,-70 Q-10,-82 0,-82 Q10,-82 10,-70 L10,-55 Q28,-45 28,-10 L28,90 Z"
      fill="#dff3fb" opacity="0.9" stroke="#8fd0e8" stroke-width="2"/>
<path d="M-28,10 L28,10 M-28,35 L28,35 M-28,60 L28,60" stroke="#8fd0e8" stroke-width="2" opacity="0.6" fill="none"/>
<ellipse cx="0" cy="-88" rx="9" ry="7" fill="#f6c9a0"/>`,
      },
      {
        slug: 'organic-cotton-swaddle',
        petalCount: 14,
        bg: ['#3a1c28', '#6b2f47', '#170810'],
        stroke: '#f5b8cf',
        centerIcon: `
<rect x="-70" y="-50" width="140" height="100" rx="14" fill="#fbeee7" opacity="0.85"/>
<path d="M-70,-50 L0,10 L70,-50" fill="none" stroke="#f3ded5" stroke-width="2.4" opacity="0.7"/>
<path d="M-70,50 L0,-5 L70,50" fill="none" stroke="#f3ded5" stroke-width="2.4" opacity="0.5"/>`,
      },
      {
        slug: 'stainless-food-container',
        petalCount: 8,
        bg: ['#22303a', '#3d5566', '#0a1014'],
        stroke: '#b9d4e3',
        centerIcon: `
<rect x="-75" y="-50" width="150" height="100" rx="16" fill="#e7f1f7" opacity="0.88" stroke="#9db9c8" stroke-width="2"/>
<line x1="-10" y1="-50" x2="-10" y2="50" stroke="#9db9c8" stroke-width="2.2"/>
<line x1="-75" y1="0" x2="-10" y2="0" stroke="#9db9c8" stroke-width="2.2"/>`,
      },
      {
        slug: 'wool-sleep-sack',
        petalCount: 16,
        bg: ['#3a2010', '#7a4420', '#170c05'],
        stroke: '#f2b98a',
        centerIcon: `
<g fill="#f5e6d8" opacity="0.92">
  <circle cx="-40" cy="-10" r="34"/>
  <circle cx="0" cy="-35" r="38"/>
  <circle cx="42" cy="-10" r="34"/>
  <circle cx="-25" cy="25" r="30"/>
  <circle cx="25" cy="25" r="30"/>
  <circle cx="0" cy="5" r="28"/>
</g>
<path d="M-15,-5 q8,10 0,20 M15,-5 q-8,10 0,20" fill="none" stroke="#caa27e" stroke-width="2" opacity="0.5"/>`,
      },
    ],
  },
}

function main() {
  const [, , setName, ...rest] = process.argv

  if (!setName || setName === '--list') {
    console.log(`Available sets: ${Object.keys(SETS).join(', ')}`)
    for (const [name, set] of Object.entries(SETS)) {
      console.log(`  ${name}: ${set.items.length} item(s) -> ${set.outDir}/${set.prefix}-<slug>.svg`)
    }
    return
  }

  const set = SETS[setName]
  if (!set) {
    console.error(`Unknown set "${setName}". Available: ${Object.keys(SETS).join(', ')}`)
    process.exit(1)
  }

  const onlyArg = rest.find((a) => a.startsWith('--only='))
  const only = onlyArg ? new Set(onlyArg.slice('--only='.length).split(',')) : null

  const outDir = join(ROOT, set.outDir)
  mkdirSync(outDir, { recursive: true })

  let written = 0
  for (const item of set.items) {
    if (only && !only.has(item.slug)) continue
    const svg = renderMandala(item)
    const file = join(outDir, `${set.prefix}-${item.slug}.svg`)
    writeFileSync(file, svg)
    console.log(`wrote ${file}`)
    written++
  }
  if (written === 0) console.log(`Nothing written (set "${setName}" has no matching items).`)
}

main()
